//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Hospital_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTEND
    {
        public int PID { get; set; }
        public short SID { get; set; }
        public short RID { get; set; }
        public int AID { get; set; }
    
        public virtual APPOINTMENT APPOINTMENT { get; set; }
        public virtual PATIENT PATIENT { get; set; }
        public virtual STAFF STAFF { get; set; }
        public virtual ROOM ROOM { get; set; }
    }
}
