//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Hospital_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT_HISTORY
    {
        public int PID { get; set; }
        public short WEIGHT { get; set; }
        public short HEIGHT { get; set; }
        public string BLOOD_TYPE { get; set; }
        public string ETHNICITY { get; set; }
    }
}
