//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Hospital_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT
    {
        public PATIENT()
        {
            this.ATTENDS = new HashSet<ATTEND>();
            this.DRUG_HISTORY = new HashSet<DRUG_HISTORY>();
            this.PREEXISTING_CONDITIONS = new HashSet<PREEXISTING_CONDITIONS>();
            this.ROOMs = new HashSet<ROOM>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string CONTACT_NO { get; set; }
        public short AGE { get; set; }
        public string GENDER { get; set; }
    
        public virtual ICollection<ATTEND> ATTENDS { get; set; }
        public virtual ICollection<DRUG_HISTORY> DRUG_HISTORY { get; set; }
        public virtual ICollection<PREEXISTING_CONDITIONS> PREEXISTING_CONDITIONS { get; set; }
        public virtual ICollection<ROOM> ROOMs { get; set; }
    }
}
