//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Hospital_Management_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APPOINTMENT> APPOINTMENTs { get; set; }
        public DbSet<ATTEND> ATTENDS { get; set; }
        public DbSet<DOCTOR> DOCTORs { get; set; }
        public DbSet<DRUG_HISTORY> DRUG_HISTORY { get; set; }
        public DbSet<NURSE> NURSEs { get; set; }
        public DbSet<PATIENT> PATIENTs { get; set; }
        public DbSet<PATIENT_HISTORY> PATIENT_HISTORY { get; set; }
        public DbSet<PREEXISTING_CONDITIONS> PREEXISTING_CONDITIONS { get; set; }
        public DbSet<ROOM> ROOMs { get; set; }
        public DbSet<STAFF> STAFFs { get; set; }
    }
}
