//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Hospital_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        public ROOM()
        {
            this.ATTENDS = new HashSet<ATTEND>();
            this.PATIENTs = new HashSet<PATIENT>();
        }
    
        public short ID { get; set; }
        public short FLOOR { get; set; }
        public string TYPE { get; set; }
        public string STATUS { get; set; }
    
        public virtual ICollection<ATTEND> ATTENDS { get; set; }
        public virtual ICollection<PATIENT> PATIENTs { get; set; }
    }
}
