//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Hospital_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public STAFF()
        {
            this.ATTENDS = new HashSet<ATTEND>();
        }
    
        public short ID { get; set; }
        public string NAME { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string SPECIALTY { get; set; }
        public string GENDER { get; set; }
    
        public virtual ICollection<ATTEND> ATTENDS { get; set; }
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual NURSE NURSE { get; set; }
    }
}
